repo:
  - any: ['.github/**/*', '.gitignore', 'README.*', '*.example', '**/.example', 'Makefile']

ansible:
  - 'ansible/**/*'

terraform:
  - 'terraform/**/*'

borg:
  - 'images/borg/**/*'

caddy:
  - 'images/caddy/**/*'

docker:
  - any: ['docker-compose.*', '**/Dockerfile']