repo:
  - '.github/**/*'
  - '.gitignore'
  - 'README.*'
  - '**/.example'
  - 'Makefile'

ansible:
  - 'ansible/**/*'

terraform:
  - 'terraform/**/*'

borg:
  - 'images/borg/**/*'

caddy:
  - 'images/caddy/**/*'

docker:
  - 'docker-compose.*'
  - '**/Dockerfile'
