version: '3.9'

volumes:
  vaultwarden_data:
  caddy_data:
  caddy_config:

services:

  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden_data:/data
      - /var/log/vaultwarden.log:/var/log/vaultwarden.log
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - INVITATIONS_ALLOWED=true
      - LOG_FILE=/var/log/vaultwarden.log
      - IP_HEADER=CF-Connecting-IP
      # Usually runs without an admin token, but can be set temporarily by `make app-configure`
      - ADMIN_TOKEN=${VAULT_ADMIN_TOKEN:-}
    secrets:
      - source: VAULTWARDEN_ENV
        target: /.env
        mode: 0400

  caddy:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/vault_caddy:${IMAGE_TAG:-latest}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_config:/config
      - caddy_data:/data
    environment:
      - PROXY_HOST=vaultwarden
      - LOG_FILE=/data/access.log
    secrets:
      - CADDY_DOMAIN
      - CADDY_EMAIL

  borg:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/vault_borg:${IMAGE_TAG:-latest}
    volumes:
      - vaultwarden_data:/data
    secrets:
      - BORG_REPO
      - BORG_SSH_PRIVATE_KEY
      - BORG_PASSPHRASE


secrets:

  CADDY_DOMAIN:
    external: true

  CADDY_EMAIL:
    external: true

  VAULTWARDEN_ENV:
    external: true

  BORG_REPO:
    external: true

  BORG_PASSPHRASE:
    external: true

  BORG_SSH_PRIVATE_KEY:
    external: true