name: Docker stack deployment
author: Joshua Stover <josh@jstover.net>
description: 'Deploy a Docker swarm project to a remote server'
inputs:

  ssh_host:
    description: Remote docker host (e.g. user@hostname)
    required: true

  ssh_key:
    description: Private key for connecting to the remote host
    required: true

  ssh_port:
    description: SSH port for the remote host
    required: false

  stack_file:
    description: Path to the docker-compose stack file
    required: false

  stack_name:
    description: Name to use for the compose stack
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: layers
  color: gray-dark

