#cloud-config

groups:
  - ssh_users

users:
  - default
  - name: ${admin_username}
    groups: adm, systemd-journal, docker, ssh_users
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${admin_public_key}
  - name: ${deployer_username}
    groups: docker, ssh_users
    lock_passwd: true
    ssh_authorized_keys:
      - ${deployer_public_key}
      - ${admin_public_key}
