#cloud-config

device_aliases:
  block_volume: /dev/sdb

disk_setup:
  block_volume:
    table_type: gpt
    layout: true

fs_setup:
  - label: vaultwarden_data
    filesystem: ext4
    device: block_volume.1

mounts:
  - ["block_volume.1", "/vaultwarden_data"]


groups:
  - ssh_users

users:
  - default
  - name: ${admin_username}
    groups: adm, systemd-journal, docker, ssh_users
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${admin_public_key}
  - name: ${deployer_username}
    groups: docker, ssh_users
    lock_passwd: true
    ssh_authorized_keys:
      - ${deployer_public_key}
      - ${admin_public_key}

runcmd:
  - echo 'Provisioned by Terraform.' >> /etc/motd
