BORG_REPO: "{{ lookup('env', 'BORG_REPO') }}"

BORG_PASSPHRASE: "{{ lookup('env', 'BORG_PASSPHRASE') }}"

BORG_SSH_PRIVATE_KEY: "{{ lookup('env', 'BORG_SSH_PRIVATE_KEY') }}"

VAULTWARDEN_ENV: "{{ lookup('file', '../../vaultwarden.env') }}"

CLOUDFLARE_ZONE: "{{ lookup('env', 'VAULT_DOMAIN') }}"

CLOUDFLARE_TOKEN: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
