- name: Add Docker CE yum repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Add OracleLinux 8 EPEL repository
  yum:
    name: oracle-epel-release-el8
    state: installed

- name: Enable OracleLinux 8 EPEL repository
  ini_file:
    path: /etc/yum.repos.d/oracle-epel-ol8.repo
    section: ol8_developer_EPEL
    option: enabled
    value: 1
    no_extra_spaces: true

- name: Remove cockpit
  yum:
    name:
      - cockpit
      - cockpit-bridge
    state: absent
    autoremove: true

- name: Upgrade packages
  yum:
    name: '*'
    state: latest
