- name: Configure
  hosts: vault
  become: true
  tasks:
    - name: OS-specific configuration
      include_tasks: "configure.{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Upgrade packages
      package:
        name: '*'
        state: latest

    - name: Install required packages
      package:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - python3-docker
          - fail2ban

    - name: Configure SELinux
      tags:
        - debug
      ansible.posix.seboolean:
        name: nis_enabled
        state: true
        persistent: true

    - name: Enable docker service
      systemd:
        daemon_reload: true
        name: docker
        state: started
        enabled: true

    - name: Initialise docker swarm
      tags:
        - docker
      community.docker.docker_swarm:
        state: present

    - name: Install docker-ingress-routing-daemon (executable)
      tags:
        - docker
        - dind
      copy:
        src: files/docker-ingress-routing-daemon/docker-ingress-routing-daemon
        dest: /usr/local/bin/docker-ingress-routing-daemon
        owner: root
        group: root
        mode: '0755'

    - name: Collect docker swarm ingress IPs
      tags:
        - docker
        - dind
      shell: ( /usr/local/bin/docker-ingress-routing-daemon 2>&1 || true ) | sed -n 's/.*ingress network IP{{":"}} //p'
      register: ingress_ip
      changed_when: false
      failed_when: ingress_ip.stdout | trim | length == 0

    - name: Install docker-ingress-routing-daemin (systemd unit)
      tags:
        - docker
        - dind
      vars:
        ingress_gateway_ip_list: "{{ ansible_play_hosts | map('extract', hostvars, 'ingress_ip') | map(attribute='stdout') | map('trim') | join(' ') }}"
      copy:
        dest: /etc/systemd/system/dind.service
        content: "{{ lookup('template', 'files/docker-ingress-routing-daemon/dind.service') }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart dind

    - name: Configure docker secrets (vars)
      tags:
        - docker
        - docker-secrets
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ lookup('vars', '{{ item.var }}') }}"
        state: present
      loop:
        - {name: BORG_REPO, var: borg_repo }
        - {name: BORG_PASSPHRASE, var: borg_passphrase }
        - {name: BORG_SSH_PRIVATE_KEY, var: borg_ssh_private_key }
        - {name: VAULTWARDEN_ENV, var: vaultwarden_env }

    - name: Configure docker secrets (file)
      tags:
        - docker
        - docker-secrets
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ lookup('file', '{{ item.file }}') | b64encode }}"
        data_is_b64: true
        state: present
      loop:
        - { name: "VAULTWARDEN_SECRET_ENV", file: "../../vaultwarden.env" }

    - name: Configure SSH server daemon
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^(# *)?{{ item.key }} \\w+$"
        line: "{{ item.key }} {{ item.value }}"
        state: present
      loop:
        - {key: "PermitRootLogin", value: "no"}
        - {key: "MaxSessions", value: "500"}
        - {key: "PasswordAuthentication", value: "no"}
        - {key: "X11Forwarding", value: "no"}
        - {key: "AllowGroups", value: "ssh_users"}
      notify:
        - Restart sshd

    - name: Enable fail2ban
      tags:
        - fail2ban
      systemd:
        daemon_reload: true
        name: fail2ban
        state: started
        enabled: true

    - name: Configure fail2ban
      tags:
        - fail2ban
      copy:
        src: "files/fail2ban/{{ item.src }}"
        dest: "/etc/fail2ban/{{ item.dest }}"
        owner: root
        group: root
        mode: '0640'
      loop:
        - {src: "vaultwarden-web.filter.conf", dest: "filter.d/vaultwarden-web.local"}
        - {src: "vaultwarden-web.jail.conf", dest: "jail.d/vaultwarden-web.local"}
        - {src: "vaultwarden-admin.filter.conf", dest: "filter.d/vaultwarden-admin.local"}
        - {src: "vaultwarden-admin.jail.conf", dest: "jail.d/vaultwarden-admin.local"}
      notify:
        - Restart fail2ban

    - name: Install fail2ban CloudFlare action
      tags:
        - fail2ban
      template:
        src: files/fail2ban/cloudflare.action.conf
        dest: /etc/fail2ban/action.d/cloudflare.conf
        owner: root
        group: root
        mode: '0640'
      notify:
        - Restart fail2ban

    - name: Create vaultwarden.log
      tags:
        - fail2ban
      copy:
        content: ""
        dest: /var/log/vaultwarden.log
        force: false
        owner: root
        group: root
        mode: '0640'


    - name: Configure logrotate
      copy:
        src: files/logrotate/vaultwarden.conf
        dest: /etc/logrotate.d/vaultwarden
        owner: root
        group: root
        mode: '0640'
        validate: /usr/sbin/logrotate -vf %s
      notify:
        - Restart rsyslog


    - name: Update MOTD
      lineinfile:
        path: /etc/motd
        line: "Configured by ansible."
        state: present


  handlers:
    - name: Restart sshd
      systemd:
        state: restarted
        name: sshd

    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Restart rsyslog
      systemd:
        name: rsyslog
        state: restarted

    - name: Restart dind
      systemd:
        name: dind
        state: restarted
        enabled: true
        daemon_reload: true
