- name: Fetch Docker Keyring
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.gpg_armored
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

- name: Add Docker CE repository
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg_armored]
      https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    update_cache: true

- name: Upgrade packages
  apt:
    name: '*'
    state: latest
    autoremove: true
    autoclean: true
