- name: "OS (RedHat): Add Docker CE yum repository"
  tags:
    - os
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: "OS (RedHat): Add OracleLinux 8 EPEL repository"
  tags:
    - os
  yum:
    name: oracle-epel-release-el8
    state: installed

- name: "OS (RedHat): Enable OracleLinux 8 EPEL repository"
  tags:
    - os
  ini_file:
    path: /etc/yum.repos.d/oracle-epel-ol8.repo
    section: ol8_developer_EPEL
    option: enabled
    value: 1
    no_extra_spaces: true

- name: "OS (RedHat): Remove cockpit"
  tags:
    - os
  yum:
    name:
      - cockpit
      - cockpit-bridge
    state: absent
    autoremove: true

- name: "OS (RedHat): Upgrade packages"
  tags:
    - os
  yum:
    name: '*'
    state: latest
