- name: "OS: Distro-specific configuration"
  tags:
    - os
  include_tasks: "os.{{ ansible_facts['os_family'] | lower }}.yml"

- name: "OS: Install required packages"
  tags:
    - os
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - python3-docker
      - fail2ban

- name: "OS: Enable SELinux"
  tags:
    - os
    - selinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  register: selinux

- name: "OS: Reboot System"
  tags:
    - os
    - selinux
  reboot:
  when: selinux.reboot_required

- name: "OS: Configure SELinux"
  tags:
    - os
    - selinux
  when: not selinux.state == "disabled"
  ansible.posix.seboolean:
    name: nis_enabled
    state: true
    persistent: true

- name: "OS: Configure SSH daemon"
  tags:
    - os
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^(# *)?{{ item.key }} \\w+$"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - {key: "PermitRootLogin", value: "no"}
    - {key: "MaxSessions", value: "500"}
    - {key: "PasswordAuthentication", value: "no"}
    - {key: "X11Forwarding", value: "no"}
    - {key: "AllowGroups", value: "ssh_users"}
  notify:
    - Restart sshd
