name: Deploy
on:
  push:
    branches:
      - master
      - deploy
      - 'deploy-*'

jobs:

  calculated_values:
    name: Calculated values for other jobs
    runs-on: ubuntu-latest
    outputs:
      tree_sha: ${{ steps.tree_sha.outputs.value }}
      deployer_username: ${{ steps.tf_deployer_username.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: tree_sha
        run: echo "::set-output name=value::$(git rev-parse HEAD:)"

  terraform_outputs:
    name: Fetch terraform outputs
    runs-on: ubuntu-latest
    outputs:
      primary_ip: ${{ steps.tfc.outputs.primary_ip }}
      deployer_username: ${{ steps.tfc.outputs.deployer_username }}
    steps:
      - uses: actions/checkout@v3
      - id: tfc
        uses: ./.github/actions/terraform-cloud-outputs
        with:
          token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          org: ${{ secrets.TERRAFORM_CLOUD_ORG }}
          workspace: ${{ secrets.TERRAFORM_CLOUD_WORKSPACE }}
          variables: deployer_username, primary_ip

  clean:
    name: Delete old packages
    runs-on: ubuntu-latest
    steps:

      - uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          repository: ghcr.io/sinex
          package-name: vault_caddy
          personal-account: true

      - uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          repository: ghcr.io/sinex
          package-name: vault_borg
          personal-account: true

      - uses: snok/container-retention-policy@v1
        with:
          image-names: vault_borg, vault_caddy
          cut-off: 1 day ago UTC
          timestamp-to-use: updated_at
          account-type: personal
          keep-at-least: 5
          skip-tags: latest
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs:
      - clean
      - calculated_values
    strategy:
      matrix:
        image: [caddy, borg]

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:images/${{ matrix.image }}"
          tags: |
            ghcr.io/sinex/vault_${{ matrix.image }}:latest
            ghcr.io/sinex/vault_${{ matrix.image }}:${{ needs.calculated_values.outputs.tree_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - calculated_values
      - terraform_outputs
      - build
    if: startsWith(github.ref, 'refs/heads/deploy')
    env:
      CONTAINER_REGISTRY: ghcr.io
      IMAGE_TAG: ${{ needs.calculated_values.outputs.tree_sha }}
      VAULT_HOSTNAME: ${{ secrets.VAULT_HOSTNAME }}
      VAULT_DOMAIN: ${{ secrets.VAULT_DOMAIN }}
      VAULT_ADMIN_EMAIL: ${{ secrets.VAULT_ADMIN_EMAIL }}
      VAULT_ORG_NAME: ${{ secrets.VAULT_ORG_NAME }}
      VAULT_SMTP_HOST: ${{ secrets.VAULT_SMTP_HOST }}
      VAULT_SMTP_USERNAME: ${{ secrets.VAULT_SMTP_USERNAME }}
      VAULT_SMTP_PASSWORD: ${{ secrets.VAULT_SMTP_PASSWORD }}
      BORG_REPO: ${{ secrets.BORG_REPO }}
      BORG_PASSPHRASE: ${{ secrets.BORG_PASSPHRASE }}
      BORG_SSH_PRIVATE_KEY: ${{ secrets.BORG_SSH_PRIVATE_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/docker-compose-deploy
        with:
          ssh_user: ${{ needs.terraform_outputs.outputs.deployer_username }}
          ssh_host: ${{ needs.terraform_outputs.outputs.primary_ip }}
          ssh_key: ${{ secrets.SSH_KEY }}
          stack_name: vault
          docker_registry: ghcr.io
          docker_username: ${{ github.repository_owner }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}
