name: Check Ansible on OracleLinux 8

on: [push, pull_request]

jobs:
  ansible-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-ansible-oraclelinux8-action
        with:
          targets: ./ansible/configure.yml
          group: all
          hosts: vault
          requirements: ./ansible/requirements.yml
