name: Linter Checks

on: [push, pull_request]

jobs:

  terraform-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main

  docker-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint Dockerfiles
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: caddy/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}