name: Linter Checks

on: [push, pull_request]

jobs:

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Lint Terraform
      uses: actionshub/terraform-lint@main


  docker-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [caddy, borg]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: dockerfilelint (${{ matrix.image }})
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: ${{ matrix.image }}/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()

    - name: Hadolint (${{ matrix.image }})
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: ${{ matrix.image }}/Dockerfile
      if: always()
