name: Linter Checks

on: [push]

jobs:

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/terraform-lint@main


  docker-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
            images/caddy,
            images/borg,
            .github/actions/crontab-lint,
            .github/actions/docker-compose-deploy
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dockerfilelint
        if: always()
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
      - uses: hadolint/hadolint-action@v3.0.0
        if: always()
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile


  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: cron_linter.sh docker-ingress-routing-daemon


  crontab-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/crontab-lint
        with:
          crontab: images/borg/crontab


  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6
        with:
          path: "ansible/"
