name: Linter Checks

on: [push]

jobs:

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/terraform-lint@main


  docker-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [caddy, borg, .github/actions/crontab-lint, .github/actions/docker-compose-deploy]
    steps:
      - uses: actions/checkout@v3
      - uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: ${{ matrix.image }}/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
        if: always()


  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: cron_linter.sh


  crontab-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/crontab-lint
        with:
          crontab: borg/crontab
